no_access = "У вас нет доступа"
hello_superadmin = "Вы - суперадмин."
seriously_complete = "Вы точно хотите завершить заявку?"
no_complete = "Статус заявки остался неизменным. Вы можете выйти в главное меню"
sent_to_achieve = "Заявка отправлена в архив"
choice_newsletter_text = "Выберите адрес для рассылки"
give_role = "Ваш функционал"
select_an_employee_for_settings = "Выберите сотрудника для настроек"
